leonardt/fault

- fault/target.py
- fault/tester.py
- fault/verilator_target.py
- tests/test_verilator_target.py
For issue #3
Added the following:
-- target.Target is the base class for all targets. It contains a very
simple interface (__init__(), run()).
-- verilator_target.Target is an implementation of target.Target for
verilator.
The verilator specific logic in tester.compile_and_run() should now go
in a separate file for each target.
Also added relevant tests.
> Move target specific logic into own class

- setup.cfg
Set pytest pep8 check line length to 80 (instead of 79).
> Modify pep8 setup file

- fault/logging.py
- tests/test_logging.py
Similar to magma logging module (magma/magma/logging.py).
> Add logging module

- fault/logging.py
- fault/python_simulator_target.py
- tests/test_logging.py
- tests/test_python_simulator_target.py
@leonardt I don't think this is complete yet. Just wanted to throw it out there to make sure it was on the right track. What do you think? I think solving issue #8 will make it obvious what to do here.
Adding backend for python simulator. Also adding test for python
simulator backend.
TODO(rsetaluri): Add tests for synchronous circuit (i.e. w/ clk).
> Add python simulator backend

- fault/actions.py
- fault/tester.py
- tests/test_action.py
- tests/test_magma_simulator_target.py
- tests/test_tester.py
- tests/test_vector_builder.py
- tests/test_verilator_target.py
Convenience methods for debugging.
For example, with this change
```diff
diff --git a/fault/magma_simulator_target.py b/fault/magma_simulator_target.py
index 8bfc66b..2b09d84 100644
--- a/fault/magma_simulator_target.py
+++ b/fault/magma_simulator_target.py
@@ -24,6 +24,7 @@ class MagmaSimulatorTarget(Target):
def run(self):
simulator = self.backend_cls(self.circuit, self.clock)
for action in self.actions:
+            print(action)
if isinstance(action, actions.Poke):
value = action.value
```
You get a nice printout, such as
```
Poke(PISO10.PI, 956)
Poke(PISO10.SI, 0)
Poke(PISO10.LOAD, 1)
Step(2, PISO10.CLK)
Poke(PISO10.PI, 255)
Poke(PISO10.SI, 0)
Poke(PISO10.LOAD, 0)
Step(2, PISO10.CLK)
Expect(PISO10.O, 1)
```
> Add __str__ methods for actions

- fault/actions.py
- fault/circuit_utils.py
- fault/tester.py
- tests/common.py
- tests/test_tester.py
Closes https://github.com/leonardt/fault/issues/16
Basically, we can't just copy test vectors any more because the actions save the associated port. My proposed solution is to add a `copy` method to a tester object, which you can call with a new circuit and clock. It copies all the actions and updates the port/clock references. It also checks that the interfaces are the same.
> Add support for copying a tester for a circuit with the same interface

- fault/actions.py
- fault/magma_simulator_target.py
- fault/tester.py
- fault/vector_builder.py
- fault/verilator_target.py
- tests/test_action.py
- tests/test_magma_simulator_target.py
- tests/test_tester.py
- tests/test_vector_builder.py
- tests/test_verilator_target.py
Only works on top level ports
Supports an optional argument `format_str` which allows you to customize how the value is printed (by default it is `%x`).
Example usage:
```python
tester.print(circ.O, "%08x")
```
Adds tests for Actions, Tester, and the magma/verilator targets.
> Add initial support for print

- fault/tester.py
- fault/value_utils.py
- tests/test_tester.py
Useful for setting up tests where you want all inputs initialized to
zero.
> Add convenience method for zeroing all inputs

- fault/actions.py
- tests/test_magma_simulator_target.py
- tests/test_verilator_target.py
Can be useful for debugging to see what the inputs are at the time of
expect failure.
Also, the error message has a stray `peek`
> Allow printing input values

- fault/verilator_target.py
- fault/verilator_utils.py
- tests/SB_DFF.v
- tests/test_include_verilog.py
Adds a parameter `include_directories` which is a list of directories to
include in the verilator command using the `-I` flag.
Also, renames the include_verilog_files parameter/field to be
`include_verilog_libraries` to more explicitly match the verilator
terminology (`-v` is use for library files.)
> [verilator-target] Add interface to add include directories

- .travis.yml
- fault/actions.py
- fault/magma_simulator_target.py
- fault/tester.py
- fault/verilator_target.py
- tests/common.py
- tests/test_action.py
- tests/test_functional_tester.py
- tests/test_magma_simulator_target.py
- tests/test_tester.py
- tests/test_verilator_target.py
Feature request from @alexcarsello. Allows you to `expect` that two ports are equal. Here's the simple test case
```
T = m.Bits(3)
class TestPeekCircuit(m.Circuit):
__test__ = False   # Disable pytest discovery
IO = ["I", m.In(T), "O0", m.Out(T), "O1", m.Out(T)]
@classmethod
def definition(io):
m.wire(io.I, io.O0)
m.wire(io.I, io.O1)
```
```
def test_tester_clock():
circ = common.TestPeekCircuit
tester = fault.Tester(circ)
tester.poke(circ.I, 0)
tester.expect(circ.O0, tester.peek(circ.O1))
check(tester.actions[0], Poke(circ.I, 0))
check(tester.actions[1], Expect(circ.O0, Peek(circ.O1)))
```
Currently this depends on the latest coreir release 
It includes test skipped due to https://github.com/rdaly525/coreir/issues/627, and workarounds for https://github.com/rdaly525/coreir/issues/625 …
> Initial peek support

- .travis.yml
- fault/actions.py
- fault/magma_simulator_target.py
- fault/target.py
- fault/tester.py
- fault/verilator_target.py
- tests/common.py
- tests/test_action.py
- tests/test_functional_tester.py
- tests/test_magma_simulator_target.py
- tests/test_tester.py
- tests/test_verilator_target.py
This separates compilation (creating a target) from running (with a set of actions). This allows the user to compile a verilator binary once, then regenerate the harness with a new set of actions. Also adds a `clear` method as a mechanism for resetting the `actions` list.
The main change here is to have `actions` be an argument to `run` (which generates the harness with the new list of actions), rather than having `actions` be an argument to the target constructor.
Let me know if you have better ideas on how to organize this.
> Refactor compile_and_run logic

- fault/verilator_target.py
- tests/test_verilator_target.py
Fixes a bug in how we generate code for `Peek`s in the verilator backend.
https://github.com/StanfordAHA/garnet/pull/122 is blocked on this.
> Fix verilator peek

- fault/system_verilog_target.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_include_verilog.py
Adds support for the `include_verilog_libraries` parameter to the system verilog target. This allows the user to provide a list of verilog files which will be passed to the simulator when running (e.g. for including standard cell libraries).
This functionality already existed for the verilator target, so I moved the interface to the `VerilogTarget` parent class and updated the test to be parametrized over target.
I have not yet added include directories because I'm not aware of how to do this with ncsim/vcs, but should be simple enough to add if we need it (and can figure out the right option to pass to the simulators).
> Sv include verilog

- fault/system_verilog_target.py
- fault/verilog_target.py
Fixes an issue for @alexcarsello where the simulator commands were using the full path of the file names including the `self.directory` field. Because the simulator commands are run inside `self.directory`, the prefix shouldn't be included in those commands. This changes the logic to only use `self.directory` when creating the test collateral (instead of also for the simulator commands)
> [system-verilog-target] Don't use directory prefix in simulator commands

- .travis.yml
- CHANGELOG.md
- README.md
- doc/actions.md
- docs/actions.html
- docs/index.html
- docs/system_verilog_target.html
- docs/tester.html
- docs/value_utils.html
- docs/verilator_target.html
- docs/verilog_target.html
- fault/__init__.py
- fault/actions.py
- fault/select_path.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/value_utils.py
- fault/verilator_target.py
- fault/verilog_target.py
- fault/verilog_utils.py
- fault/wrapper.py
- requirements.txt
- setup.py
- tests/common.py
- tests/simple_alu.v
- tests/test_include_verilog.py
- tests/test_magma_simulator_target.py
- tests/test_setattr_interface.py
- tests/test_tester.py
- tests/test_verilog_target.py
Submitting this PR with the intention of blocking @Kuree. Basically, we need the ability to expect/peek internal signals. One issue is how to do this with wrapped verilog.
@Kuree, I think this should give the basic functionality required to expect values on the internal registers of the wrapped PE. You need to use `verilator_include` to include the public module (verilog module), you need to add a comment in the verilog file on the signals you want to be public, and then you can use `WrappedVerilogInternalPort`. It's clunky, but let me know if this gets you the functionality you require. Can you try checking out and installing this branch of fault? There are docs at https://github.com/leonardt/fault/blob/9c978320c970692b051bb4eaa11420f59d9f6910/doc/actions.md#wrappedveriloginternalport, …
> Add primitive support for internal signals

- .travis.yml
- fault/__init__.py
- fault/actions.py
- fault/cosa_target.py
- fault/symbolic_tester.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/utils.py
- fault/verilator_target.py
- fault/verilog_target.py
- setup.py
- tests/common.py
- tests/test_symbolic_tester.py
This adds minimum working support for the ability to specify constrained random tests and formal checks using the same interface.
The pattern is:
* Assumptions are specified on specific ports: `tester.circuit.<port>.assume(lambda <IO> : <smt_formula>)`
* Guarantees are specified on specific ports: `tester.circuit.<port>.guarantee(lambda <IO> : <smt_formula>)`
When using the `verilator` target, assumptions are used to filter input test vectors. Guarantees are emitted on every `Eval` action to assert that the property is true.
When using the `cosa` target, assumptions are mapped to the `assumptions` field in the problem file, and guarantees become `formula`s.
There's still quite a bit work to do here, a partial list is:
* Specify the supported language for formulas. This is identical to …
> Adds initial implementation of the assume guarantee

- fault/magma_simulator_target.py
- fault/random.py
- fault/system_verilog_target.py
- fault/test_vector_generator.py
- fault/test_vectors.py
- fault/tester.py
- fault/value_utils.py
- fault/vector_builder.py
- fault/verilator_target.py
- setup.py
- tests/test_functional_tester.py
- tests/test_magma_simulator_target.py
- tests/test_symbolic_tester.py
- tests/test_test_vectors.py
- tests/test_tester.py
- tests/test_value_utils.py
- tests/test_vector_builder.py
- tests/test_verilator_target.py
- tests/test_verilog_target.py
Initial migration to `hwtypes`, adds support for poking tuples
> Updates for magma sequential pe1

- fault/system_verilog_target.py
- fault/verilator_target.py
Old code assumed that 32 bits was the max size for an integer, this code now chooses 64 versus 32 depending `platform.architecture()`
> Determine max_bits from architecture

- fault/select_path.py
This is a very simple change which adds a `debug_name` property to the SelectPath class. This is for debug printing. Currently, if we try to print a test object with `Expect` actions, we get the following error:
```
File "./test_exercise_1.py", line 31, in <module>
main()
File "./test_exercise_1.py", line 28, in main
test_v1()
File "./test_exercise_1.py", line 23, in test_v1
print(simple_alu_tester)
File "/home/makai/repos/fault/fault/tester.py", line 219, in __str__
s += f"    {i}: {action}\n"
File "/home/makai/repos/fault/fault/actions.py", line 23, in __str__
return f"{type_name}({self.port.debug_name}, {self.value})"
AttributeError: 'SelectPath' object has no attribute 'debug_name'
```
This change just ensures that there's a `debug_name`. Let me know if there's a better way to do this …
> Add debug_name property to SelectPath

- fault/actions.py
- fault/cosa_target.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_action.py
- tests/test_symbolic_tester.py
- tests/test_tester.py
- tests/test_verilog_target.py
Initial implementation of loop action for TBG, only tested on verilator.
Here's the generated `main` for `test_tester_loop`
```cpp
int main(int argc, char **argv) {
Verilated::commandArgs(argc, argv);
VArrayCircuit* top = new VArrayCircuit;
#if VM_TRACE
Verilated::traceEverOn(true);
tracer = new VerilatedVcdC;
top->trace(tracer, 99);
mkdir("logs", S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH);
tracer->open("logs/ArrayCircuit.vcd");
#endif
top->I = 0;
for (int __fault_loop_var_action_0 = 0; __fault_loop_var_action_0 < 7; __fault_loop_var_action_0++) {
top->I = __fault_loop_var_action_0;
top->eval();
main_time++;
#if VM_TRACE
tracer->dump(main_time);
#endif
my_assert(top->O, __fault_loop_var_action_0, 1, "ArrayCircuit.O");
}
#if VM_TRACE
tracer->close();
#endif
}
```
> Loop action

- fault/verilator_target.py
- tests/test_verilator_target.py
- Add a skip verilator option so that TBG can reuse existing binary. In TBG it will be used together with `skip_compile=True` to skip the magma circuit, verilog, and verilator compilation.
- Add a test to confirm the functionality.
> Add initial implementation of skipping verilator build

- fault/actions.py
- fault/cosa_target.py
- fault/file.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/common.py
- tests/test_action.py
- tests/test_tester.py
We should do a design review on the interface and clean it up, but this should be sufficient for implementing TBG.
Right now it assumes that files are read with a fixed chunk size (number of bytes) specified when a file is open. Reading a file is done using the `file_read` method, however this reads into a singleton, pre-declared buffer (based on a fixed chunk size). So two calls to read will write to the same buffer (right now the interface gives an illusion that the old read value could be stored). We could remedy this by generating a new buffer for each read, but this would cause space consumption to grow linearly with number of independent reads (We could leverage some analysis at the python level to determine the lifetime of read values, but this would be complex and I suspect …
> Initial support for File IO

- fault/config.py
- fault/tester.py
- tests/build/.gitignore
- tests/test_config.py
Addresses https://github.com/leonardt/fault/issues/95
> Add config option for  callee_file_dir

- fault/system_verilog_target.py
- Add switch to suppress warnings.
- Add switch to dump VCD
- Add parameter to specify the number of cycles
> Enhancement to ncsim target

- .travis.yml
- fault/system_verilog_target.py
- tests/common.py
- tests/test_setattr_interface.py
- tests/test_tester.py
Fills out basic support for file IO actions in the system verilog backend, based on the `poke-x` branch because I needed some SV target related changes
> Add basic support for SV file io and poking X values

- fault/actions.py
`==` corresponds to instancing a `mantle.EQ` circuit for magma circuit ports.  For the actions `__eq__` method we want to check equality for testing purposes (e.g. compare a generated action sequence versus a manually crafted expected action sequence), so it should be using `is` instead of `==` to check object equality (versus just creating an EQ circuit).
> Use is instead of == for port equality

- fault/system_verilog_target.py
- fault/verilator_target.py
- tests/test_tester.py
- tests/test_verilog_target.py
Fixes sub issue in https://github.com/StanfordAHA/lassen/issues/66 where the verilator command was failing silently
> set pipefail when running verilator command

- fault/random.py
- fault/system_verilog_target.py
- fault/verilator_target.py
- tests/common.py
- tests/test_constrained_random.py
- tests/test_tester.py
(based on patch-pipefail)
Fixes the logic for compiling signed values to verilator. Basically, verilator always uses the unsigned representation as a C data type, so we need to convert all negative values into their unsigned bits representation. The logic already existed, but was too conservative (it only checked if the port was type as a signed value, but there are cases where expect a signed value on an unsigned port, such as in the case of the signed mode of the PE)
> Fix logic for signed expect/poke

- fault/verilator_target.py
Whenever the high bit for the input is high, i.e. when the value is larger than `0x80`, the current fault will pad 1's to make an negative number. This patch use masks to mask them off.
That's the cause that why `verilator` failed in `GarnetFlow` but `ncsim` works: https://github.com/StanfordAHA/GarnetFlow/commits/master
EDIT:
Travis version is working with this fix: https://travis-ci.com/StanfordAHA/GarnetFlow/builds/112535673
> fix input values due to the change for signed values

- fault/system_verilog_target.py
Fixes issue introduced in https://github.com/StanfordAHA/lassen/pull/95 where a 66 bit constant value was generated in system verilog and ncsim complained with: 
```
inst = 21040819108348690454;
--
| \|
| ncvlog: *W,INTOVF (WrappedPE_tb.sv,37\|34): bit overflow during conversion from text [2.5(IEEE)] (32 bits).
```
This changes the system verilog backend to always emit the size of the integer literal using the `<size>'d<value>` syntax.
> Explicitly set integer literal size in SV backend

- fault/__init__.py
- fault/power_tester.py
- fault/system_verilog_target.py
- tests/test_power_domains.py
- tests/verilog/simple_alu_pd.sv
This adds a `PowerTester` class that adds the methods:
* `add_power` - marks a port to be generated as `supply1`
* `add_ground` - marks a port to be generated as `supply0`
* `add_tri` - marks a port to be generated as `tri`
When the `Tester` is compiled to a SV test bench, the marked ports are generated as the specified type (as opposed to the default behavior with `reg` for inputs and `wire` for outputs)
> Initial support for testing power domains

- fault/system_verilog_target.py
- Using shifts instead of array for larger inputs
- Should support arbitrary chunk size
- Tested with `chunk_size=2` with GarnetFlow
Is there any easy way to create a wide input circuit and test in fault?
> Fix file IO with chunk_size > 1

- fault/system_verilog_target.py
Addresses issue where `ncsim` will not recompile a test bench if the new test bench file is generated within 1 second of the previous test bench file, see https://github.com/StanfordAHA/lassen/issues/111.
This forces fault to, by default, check whether the test bench exists, if so, diff the modification timestamp on the new file with the old file. if the new file is less than or equal (handling the case when this happens multiple times in a row), fault sets the new file to be "newer" than the old file.
> Timestamp edit

- fault/file.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/verilator_target.py
- tests/test_action.py
- tests/test_tester.py
Reverts default file IO behavior to be little endian (the semantics got mixed up because Pythons `file.write` method is weird and caused some semantic mismatch in the expected behavior and actual behavior) and adds a parameter to file open to select endianness.
> Add support for both endian modes

- fault/wrapper.py
- tests/test_select_model.py
This test demonstrates the basic capability in fault for selecting between two different implementations of the same module. The goal is to enable the efficient simulation of mixed signal designs by allowing the user to select between different implementations of the same module. For example, the user might wish to simulate a portion of the design using a behavioral model, another portion using the netlist representation, and another portion using a SPICE simulation.
Planned extensions are a better interface for selecting the desired implementation (rather than just passing the right include directory) and the ability to select the desired implementation on a instance basis (rather than just a per-module basis).
> Add a basic example for selecting two different implementations of the same definition

- fault/system_verilog_target.py
- fault/util.py
- tests/test_env_mod.py
Added a few features to address issues encountered in a specific CAD system:
1) The SystemVerilogTarget now has an optional "sim_env" argument that allows the user to specify a custom environment for running the simulation command.  This is needed for example if CAD tools are using scripts that except "python" to point to a Python2 install, but the user is running fault from a Python3 conda env.
2) The SystemVerilogTarget now writes STDERR to the logging.INFO level in addition to STDOUT.  This is helpful for debugging because ncsim writes certain license errors to STDERR, not STDOUT.
3) Added remove_conda() to fault/util.py.  This utility function removes path entries (if any) that start with the CONDA_PREFIX.
4) Added a new test "test_env_mod" to test out these features.  It passes …
> Allow more control of env and debug printing in the system-verilog target

- fault/system_verilog_target.py
- tests/test_ext_vlog.py
- tests/verilog/myinv.v
These commits span updates to the ncsim, vcs, and iverilog simulators in SystemVerilogTarget to make it easier to work with external files:
1. There is no file added to the source file list for the DUT itself when **ext_model_file=True**.  This, combined with the existing **ext_libs** option, gives the user an option to point to external verilog files rather than copying them over to the build directory outside of fault.  Perhaps in the future, when **skip_compile=True**, **ext_model_file** should default to **True** as well.  But I didn't want to break existing programs that depend on the current behavior.
2. The generation of commands for ncsim, vcs, and iverilog are moved into separate methods to make it easier to make simulator-specific updates in the future.
3. The files specified by …
> Working with external verilog files

- fault/system_verilog_target.py
- fault/tester.py
- tests/test_def_vlog.py
- tests/test_while_loop.py
- tests/verilog/clkdelay.sv
- tests/verilog/defadd.sv
Depends on pull request #139 
1. Define variables can now be specified to a SystemVerilogTarget via the **defines** argument.  This can be a convenient manner to pass arguments into existing verilog code.
2. Added a test for the while loop functionality in fault (tests/test_while_loop.py)
3. Added support for UnaryOp to SystemVerilogTarget.
4. Added wait_until_high/wait_until_low/wait_until_posedge/wait_until_negedge into the Tester.  These are not implemented as actions but instead are built from the _while() and step() commands.
> Define variables and wait_until_(high|low|posedge|negedge)

- examples/myinv.py
- examples/myinv.sp
- examples/sram_snm.py
- examples/sram_snm.sp
- fault/__init__.py
- fault/actions.py
- fault/cosa_target.py
- fault/select_path.py
- fault/spice.py
- fault/spice_target.py
- fault/subprocess_run.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/tester_samples.py
- fault/verilator_target.py
- fault/verilator_utils.py
- fault/verilog_target.py
- fault/verilogams.py
- fault/verilogams_target.py
- tests/spice/my_init_cond.sp
- tests/test_init_cond.py
- tests/test_verilog_target.py
The biggest change from this PR is more unified handling of subprocess calls for SystemVerilog, Verilator, VerilogAMS, and spice targets, through a "deluxe" version of subprocess.run that supports real-time output.  Other updates include exposing some more spice-level simulation capabilities and adding more examples.  Details included below.
1. Added capability to print out STDOUT lines as they come in.  Lines can be printed using logging or regular print(), depending on the optional **disp_type** argument.  This is useful for long simulations in which realtime output is helpful.  (STDERR is printed out in its entirety after the process run completes.)
2. To make the output easy to read, prepended logging info is temporarily disabled while running subprocess_run (otherwise every line …
> Real-time subprocess output; initial conditions and selective probing for Spice.

- fault/spice_target.py
- fault/subprocess_run.py
- fault/system_verilog_target.py
- fault/verilator_target.py
- fault/verilator_utils.py
- tests/common.py
- tests/test_setattr_interface.py
- tests/test_verilog_target.py
It appears that https://github.com/leonardt/fault/pull/150 disabled printing errors. When verilator fails due to an assertion, that pull request ends the program before emitting stderr. This adds back printing stderr.
Did I add back the error printing in the correct place?
> Print Errors

- fault/tester.py
- fault/verilator_target.py
- fault/verilog_utils.py
- tests/test_setattr_interface.py
- tests/test_tester.py
- tests/test_verilog_target.py
Fixes https://github.com/leonardt/fault/issues/160 by improving the tester logic to recurse when handling general arrays (this logic was added for tuples, but not arrays). Now the tester logic should properly recurse for both array and tuple types.
> Improve handling of nested types

- fault/spice_target.py
- fault/system_verilog_target.py
- tests/test_def_vlog.py
- tests/test_inv_tf.py
- tests/test_param_vlog.py
- tests/test_real_val.py
- tests/test_verilog_target.py
Before, fault was inserting #5 delays for every poke action, as a result the timing of the waveforms was off as it shows each poke action occurring during a different timestep.  I'm not sure why this was included, but removing it makes the timing more appropriate (delays only occur with clock events) and the tests pass.
There is still a `delay` parameter for poke actions that can be supplied explicitly by the user, this just removes the default delay for all pokes.
Also adds a small change to support vcd generation with iverilog
> Remove extraneous timesteps in action generation

- .travis.yml
- fault/system_verilog_target.py
Currently Icarus Verilog support is not checked as part of Travis or BuildKite tests.  This PR adds Icarus Verilog to the list of simulators tested with Travis, and fixes a few minor bugs causing some tests to fail when run using Icarus Verilog.
Details:
1. Travis Linux distro upgraded to "bionic" from "xenial" so that a modern **iverilog** version could be used (in particular, we need one supporting the "-g2012" flag)
2. Icarus Verilog is installed as a package for Linux and OSX targets on Travis.
3. Waveform dumping is fixed for Icarus Verilog using code from PR #180.
4. File writing is fixed for Icarus Verilog.  $fwrite doesn't work properly for Icarus Verilog when dealing with individual bytes because it won't write the byte "0x00".  As a result, for the **iverilog** simulator the …
> Add Icarus Verilog to Regression Testing

- fault/tester.py
- tests/test_tester.py
Catches issue when clock is initialized to X for system verilog test benches.  In the future, we will turn this into an error, but for now we just issue a warning so we don't break existing code.
> Add warning for no initialized clock

- .buildkite/pipeline.yml
- fault/subprocess_run.py
- fault/system_verilog_target.py
- tests/common.py
- tests/test_bidir.py
- tests/test_hi_z.py
- tests/test_tester.py
This PR adds a new option for running SystemVerilog simulations using Vivado.  This option can be used by setting simulator='vivado' when invoking **compile_and_run**.
Vivado support is tested as part of the regression flow using the existing fpga-verif-* BuildKite agents.
Details:
1. Since Vivado can produce one of several error strings, the **subprocess_run** command was updated to allow the **err_str** argument to be a single string, a list of strings, or a regex pattern (re.Pattern). 
2. The file I/O tests in tests/test_tester.py had to be updated to pass input and output file locations as absolute paths, because the Vivado working directory is not the same as the Python working directory.
3. tests/test_bidir.py and tests/test_hi_z.py skip the Vivado simulator since it does not …
> Add support for Vivado as a simulator

- .buildkite/pipeline.yml
- .travis.yml
- fault/system_verilog_target.py
- fault/util.py
- fault/verilator_target.py
- fault/verilator_utils.py
- fault/verilog_target.py
- tests/test_kratos_debug.py
- Modified backend to handle both verilator and system-verilog outputs.
- Introduced a flag called `use_kratos` at top level.
- Added tests to test out loading runtime directly as well as a simple ALU test for both verilator and ncsim. The ALU is copied from the magma test.
- User needs to install `kratos_runtime` separately as it's not required to use fault.
- `kratos_runtime` currently only has native build for linux systems. I will try to figure out how to build it on macos later, but it's not high priority on my list since ncsim/vcs can't run on macos.
I will add `vcs` tests as a separate PR.
I think we should refactor `build_kratos_debug_info` as a utility function magma. I just copied it here, which should be refactored.
> Kratos debugging system integration

- fault/system_verilog_target.py
- tests/test_verilog_target.py
Verilator effectively uses non-blocking semantics because pokes are staged until `eval` is called.  This updates the system verilog target to do the same by using non-blocking assign.
> Use non-blocking assign for SV poke

- fault/actions.py
- fault/cosa_target.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_tester.py
Allows the assertion of generic expressions (rather than just expecting on port values), e.g.
```
tester.assert_((tester.circuit.O[0] | tester.circuit.O[1]) == 0b01)
```
> Add generic assert_

- fault/tester.py
- tests/test_tester.py
Adds the ability to poke/expect on a slice of bits, e.g.
```
tester.circuit.I[1:] = 0b01
tester.eval()
tester.circuit.O[1:].expect(0b01)
```
> Add support for poke/expect slice

- examples/sram_snm.py
- fault/__init__.py
- fault/spice_target.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/tester_samples.py
- fault/verilator_target.py
- fault/wrapped_internal_port.py
- setup.cfg
- tests/test_bidir.py
- tests/test_ext_vlog.py
- tests/test_hi_z.py
- tests/test_setattr_interface.py
- tests/test_tester.py
This PR contains miscellaneous fixes for bugs encountered while testing multi-target capabilities with designs generated by OpenRAM.  In rough order of importance:
1. **expect_strict_default** now default to **True** for testers.  This means that if the user doesn't specify otherwise, **expect** actions will now use a strict equality check.  It is possible that with this change in default, existing tests written users may fail.  However, test failures caused by this change would almost certainly represent true bugs that users should know about.
2. The testbench generated by SystemVerilogTarget now includes a **`timescale** directive at the top.  This is necessary for **iverilog** because the timescale cannot be specified as a command-line argument for that simulator (and therefore actions …
> Fixes for bugs found when implementing OpenRAM experiment

- fault/system_verilog_target.py
- fault/verilator_target.py
- fault/verilator_utils.py
- fault/verilog_target.py
- tests/test_coverage.py
This maybe a duplicate of #65.
What does this PR do:
- Add flag `coverage` to all targets
- Tested on `ncsim` and `Verilator`. Haven't tried `vcs` yet since I'm not an expert in `vcs`; someone needs to help me out there.
- For `Verilator`, the coverage file can be parsed directly, whereas for `ncsim` we need `IMC` tools since it's a gzipped file linked to its compiled model. `kratos` has built-in ability to parse both format. Maybe there is an opportunity for tight integration so that fault can digest coverage information through `kratos`.
> Add coverage command to verilator and ncsim

- fault/system_verilog_target.py
Only use read access flags when dumping VCD. Otherwise no access flags. This should speed up simulation in most cases.
Side note:
I noticed that buildkite agents is blocked by a PR which seems to be run into infinite loop: https://buildkite.com/stanford-aha/fault/builds/1074#e2e03ea3-43f4-40e7-a62e-9de57226e1a2
We should probably set an up limit on how long a test should run on buildkite.
> Optimize ncsim flag usage

- fault/tester.py
- fault/verilator_target.py
- tests/test_tester.py
#207 
value = loop.file_read(file_in)
loop.expect(circ.O, value)
verilator works, generated system-verilog looks legit
> Allow expect to use file_read

- .travis.yml
- fault/wrapper.py
This adjusts the code so that it will raise an AttributeError (implicitly) rather than explicitly raising a plain Exception so `hasattr` will work.
> Raise attribute error instead of exception

- .buildkite/pipeline.yml
This one-liner simply adds a 60 min timeout to BuildKite tests to prevent tests that are hanging from clogging the BuildKite queue.
> Add timeout for BuildKite tests

- fault/__init__.py
- fault/system_verilog_target.py
- fault/tester/__init__.py
- fault/tester/staged_tester.py
- fault/tester/synchronous.py
- fault/verilator_target.py
- tests/test_tester/test_core.py
- tests/test_tester/test_synchronous.py
This adds an initial version of the synchronous tester.  This removes the ability to call `eval` and `step` directly, and instead presents an `advance_cycle` interface (which call step internally).
During code generation, `step` translates to `#5` (where 5 is parametrizable) which corresponds to a half-cycle.  `advance_cycle` always advances two steps (so you get a `#10` out).  The synchronous tester requires a clock, and this clock is used to generate an `always #5 CLK = ~CLK`.  Again the delay is parametrizable.  In the future, we could add support for multiple, parallel clock drivers, but I don't think this is an immediate use case.
The verilator target doesn't make any changes to the code generation currently because I think the interface should satisfy the desired behavior, but we …
> Init synchronous tester

- fault/system_verilog_target.py
This PR fixes two small issues in the way TCL files are generated for running Vivado simulations.
* `` `define `` macros containing literal double-quotes are now supported.  This already seems to be supported in the other simulators.
* Paths with spaces are now supported (for the build directory, source files, library files, and include directories).  The only other simulator that seems to support this is ``iverilog``.
Though minor, these updates are useful for me because they allow me to pass path information into Verilog code via `` `define `` macros (e.g., the path to a file to be used for ``$readmemb``).
> Fix minor bugs in Vivado TCL generation

- fault/tester/staged_tester.py
- tests/test_tester/test_core.py
This has been requested to make things simpler, I don't think it should break any existing code and seems like a reasonable default (rather than using X in SystemVerilog), it also makes verilator/SV consistent.
> Initial clocks to zero

- fault/system_verilog_target.py
This allows users to include necessary files before the top, e.g. using `-f ../file_listings.f`.  I'm hoping that this doesn't affect the use of built-in options and that the user will be responsible for ordering their own custom flags.
> Insert flags before other command options

- fault/tester/staged_tester.py
- fault/tester/synchronous.py
- fault/verilator_target.py
- tests/test_tester/test_core.py
The default clock logic was being inherited by sub-testers (e.g. for if/while loops) which was causing an unexpected setting of the clock to zero inside the TB
> Fix clock init bug

- .buildkite/pipeline.yml
- .github/workflows/deploy.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- doc/property.md
- fault/__init__.py
- fault/property.py
- fault/sva.py
- tests/test_property.py
Initial prototype of https://github.com/leonardt/fault/issues/240
Seems like we should be able to pull this off.  Will also add an example of the sva syntax.
For now we just compile to inline_verilog, eventually we should add corresponding coreir primitives and compile to that representation.
Unforuntately, verilator does not support the concurrent assertion syntax (at least the ## operator was causing an error. (also see https://www.veripool.org/projects/verilator/wiki/Manual-verilator#Assertions).
Fortunately, this gives us a good reason to support compiling these to pono (next gen CoSA, CC @makaimann) to test this feature in the open source environment.
There's still some work to organize the property code (e.g. class hierarchy and reuse for the infix operator logic, as well as the …
> Property Prototype

- .buildkite/pipeline.yml
- .github/workflows/deploy.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
This small PR gets the BuildKite and GitHub Actions tests passing again by constraining ``pytest`` to use a version number less than ``6.x.x``.
While fixing that issue, I found a separate problem in the ``MacOS Test`` on GitHub Actions.  ``gmp``, ``mpfr``, ``libmpc``are now installed by default; ``gmp`` and ``libmpc`` are the latest version whereas ``mpfr`` was an older version.  This appears to have caused an error when ``brew install`` was used.  ``brew upgrade`` fixed the problem.
> Resolve pytest and brew issues

- fault/select_path.py
- fault/system_verilog_target.py
- setup.py
- tests/test_error_handling.py
- tests/test_top_module.py
- tests/verilog/error_task.sv
- tests/verilog/fatal_task.sv
- tests/verilog/myinv_extra_module.v
This small PR fixes issue #252 by moving the position of ``-s`` for ``iverilog``.  It also includes a test of the top module selection feature, ``test_top_module.py``, pulled from a commit a few months back that was not merged.
It also fixes a small issue in which simulations that exited with ``$fatal`` were not raising exceptions if the simulator was ``iverilog`` or ``vcs``.  There is now test called ``test_error_handling.py`` to check this in the future, for both the ``$fatal`` and ``$error`` system tasks.
> Fix iverilog top module selection on macOS

- fault/verilator_target.py
- tests/test_tester/test_core.py
Follow up to https://github.com/leonardt/fault/pull/194 to support the same pattern for bitwise peek of verilator values (verilator stores bits as C scalars, so we need to use masking to fetch the bit of interest)
> Add support for bitwise peek

- fault/tester/base.py
- tests/test_tester/test_synchronous.py
Traverses the interface and uses a clock port if there is only one.  If
there are multiple, we ask the user to choose one explicitly rather than
guessing.
> Add Tester logic to find default clock

- fault/property.py
- tests/test_property.py
Fault follow up to https://github.com/phanrahan/magma/pull/832 (depends on it)
Wires generated via inline verilog and fault for the assertion logic now have a special prefix, making it easy to filter out lint related unused warnings when they are only used inside an assertion that's disabled via a macro.
> Add assertion wire prefix

- fault/tester/control.py
- fault/tester/staged_tester.py
- fault/tester/synchronous.py
- tests/test_tester/test_control.py
- tests/test_tester/test_core.py
Before, using a control structure such as `tester._if` would produce a
StagedTester instance.  This is problematic when using a
SynchronousTester, since the produced tester doesn't inherit the
expected methods (e.g. advance_cycle).
Also fix unrelated magma error from missing `m.enable` cast (regression introduced in latest magma release)
> Control actions should produce Tester based on current subclass

- doc/property.md
- fault/property.py
- tests/test_property.py
Allows the user to provide a list of compile guards (useful if some properties should require two defines).  We can't use `&&` inside `ifdef` so we have to generate nested `ifdef` statements.
> Nested compile guards

- fault/actions.py
- fault/system_verilog_target.py
- fault/tester/control.py
- fault/tester/staged_tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_fork.py
This is a prototype implementation of `fork` presented in #277 
```Python
tester = fault.Tester(dut)
proc1 = tester.fork("proc1")
proc2 = tester.fork("proc2")
for i, proc in enumerate([proc1, proc2]):
proc.poke(tester.circuit.I[i], 1)
proc.eval()
proc.expect(tester.circuit.O[i], 1)
tester.join(proc1, proc2)
```
Name is required for each forked process so it's easy to identify and useful for the waveform debugging. The current implementation should also support tested fork, as long as `join()` is called at the process, e.g. `proc.join(proc3, proc4)`.
Here is generated SV:
```SystemVerilog
initial begin
fork
begin : proc1
I[0] <= 1'b1;
#1;
if (!(O[0] === 1'b1)) begin
$error("Failed on action=0 checking port dut.O[0] with traceback /home/keyi/workspace/fault/tests/test_fork.py:24.  Expected …
```
> Add fork to systemverilog target

- doc/property.md
- fault/expression.py
- fault/infix.py
- fault/property.py
- tests/test_property.py
Adds 2 more complex assertion examples to the documentation and tests.
Minor improvement to make them work:
* need to support expressions with property constructs (e.g. `value != f.past(value, 2)`).  For now, we piggy back on fault's expression language used for peek values.  In the future, we should consider supporting this in the downstream tools (e.g. we can treat `f.past(value, 2)` as a verification instance.  I think we can just represent these structures in the graph, but we probably want to group them together so they're code generated separate from the RTL (we don't want verification code to introduce RTL-like instances that may affect synthesis or cause the synthesis/verification code to have a mismatch).
> Assert examples

- fault/__init__.py
- fault/expression.py
- fault/system_verilog_target.py
- fault/verilator_target.py
- tests/test_expressions.py
Needed for floating point tests (off by one errors mean we should be checking `abs(value - expected) <= 1`
> Add support for abs, max, min expressions

- fault/value_utils.py
- fault/verilator_target.py
- tests/test_tester/test_core.py
It turns out fault converts signed values in poke/expect to unsigned
values (see process_signed_values).  This is because verilator uses
unsigned C types for the ports (even though in magma it may be an SInt).
I also updated the var test's interface to be more consistent by using
BitVector and SIntVector instead of m.Bits (since this is testing I
think it makes sense to use the hwtypes versus magma types).  I had to
make a small change to make_value to support that (no conversion is
necessary since we're already using an appropriate BitVector type).
I remove the signed specific cdoe for the var poke since it's not needed
(since the poke value will be converted to unsigned by
process_signed_value, we should store it as unsigned, the same way that
verilator does it).
This is similar to how …
> Add var poke test for signed values

- doc/assert_immediate.md
- fault/__init__.py
- fault/assert_immediate.py
- fault/verilator_target.py
- tests/test_assert_immediate.py
This is like assert immediate, except it's only run at the end of
simulation.
Also needed to update the verilator test bench to call `top->final();`
which is required to mark the end of simulation (and thus trigger the
evaluation of final blocks such as these assertions).
> Add support for assert final

- doc/assert_immediate.md
- fault/__init__.py
- fault/assert_immediate.py
- fault/assert_utils.py
- fault/property.py
- fault/verilator_target.py
- tests/test_assert_immediate.py
- tests/test_property.py
In verilog, assertions are "behavioral" statements so they need to be
contained within a block such as always or initial (compared to
structural statements such as module instancing or assignment).  Before,
we used always @(*), however initial is preferred for some tool
compatability an the effect should be the same (since it's an immediate
assertion, it doesn't really make sense to have it sensitive to anything
other than *, so we can remove the code related to other events).
> Simplify assert immediate to use initial block

- fault/actions.py
- fault/system_verilog_target.py
- fault/tester/staged_tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_protocol.py
- tests/test_pysv.py
Separates make_call into two functions: one for an expression and one
for a statement.
Reworks the backend call logic to treat it as an expression rather than
a value (also adds a test that uses it in an expression).
Call statements are useful for making calls to a model that don't
return a value (e.g. just manipulates the state)
> Add support for call statements

- fault/__init__.py
- fault/actions.py
- fault/pysv.py
- fault/tester/control.py
- fault/tester/staged_tester.py
- fault/tester/synchronous.py
- fault/verilator_target.py
- tests/test_pysv.py
A monitor is a pysv class that defines an `observe` function that is
invoked every time advance_cycle is called.
The arguments to the observe functions refer to circuit ports by name
(in the future we could add support for internal signals).
> Add basic support for pysv monitor

- .gitignore
- fault/__init__.py
- fault/pysv.py
- fault/system_verilog_target.py
- fault/tester/synchronous.py
- tests/test_pysv.py
In the verilog simulation, product types are flattened into leaf ports.  This adds logic to the monitor code that allows the user to provide a type annotation on an argument that is a product.  When encountering product arguments, the observe function will be rewritten to accept the flattened arguments, and a small snippet of code is inserted into the function to reconstruct the original product argument from the flattened arguments.  For now, we use SimpleNamespace to provide dot notation on the product fields.  In the future, we should figure out a way to pass the magma type converted to hwtypes to the pysv class and use that to reconstruct the original argument.
Support for nested array arguments will be added next.
> Add support for monitor with product type arguments

- fault/system_verilog_target.py
- tests/test_system_verilog_target.py
This allows checking that a value is X, which could be useful for
verifying initialization behavior.
> Add support for compiling UnknownValue

- fault/tester/staged_tester.py
- tests/test_tester/test_core.py
- tests/test_while_loop.py
If you try to call if/while with a magma value, raise a helpful error
asking you to use peek, rather than emitting bad code downstream.  We
need the user to call `peek` in general so you can do things like
expressions (e.g. ~magma_value) which are then code generated in the
test bench.  We could implicitly covert a plain magma value, but then
this would be confusing because ~magma_value wouldn't work since this
would try to instance circuits outside of a circuit definition, so for
consistency this enforces that all values referred to in the test bench
are passed through the peek logic.
> Add error message for implicit peek of magma value

- fault/__init__.py
- fault/ready_valid.py
- fault/tester/staged_tester.py
- tests/test_ready_valid.py
- tests/test_system_verilog_target.py
* Automatically lift signals that are not covered by sequences, this
allows the user to control them from the test bench (e.g. tie to a
constant, change over time)
* Provide a Tester abstraction for the more general use case of test
bench controlling signals while sequences are being processed
* Adds some convenience/abstraction APIs:
* `finish_sequences` will run the test bench until the done signal
is high (all sequences are processed)
* `expect_sequences_finished` will check that the done signal is
high (important if the user is manually controlling the test
clock, otherwise some sequences may be left unfinished/unchecked)
> ReadyValidTester improvements

- fault/tester/base.py
Should only descend into tuple/array if there's a nested clock type, otherwise skip (avoids lazy children elaboration when possible).
> Avoid traversing arrays/tuple in clock logic
