- fault/tester.py
- fault/verilator_target.py
Addresses https://github.com/leonardt/fault/issues/2
This was a one-to-one copy, we should review and refactor this code, but unfortunately my nested array support changes depend on changes to this code, so I'd prefer that we refactor after I've merged those changes in.
> Migrate magma verilator code into fault

- .travis.yml
- fault/array.py
- fault/tester.py
- fault/verilator_target.py
- setup.cfg
- tests/common.py
- tests/test_tester.py
- tests/test_verilator_target.py
Adds support for nested arrays in the IO. Adds two tests, one for the testvector construction, another for running a simple feedthrough module in verilator.
> Nested arrays

- tests/common.py
- tests/test_tester.py
- tests/test_verilator_target.py
Factor out common circuits into tests/common.py. Furthermore, each of
these circuits are just simple pass through circuits, so there is a
common generator for all of them (with type T as a paramter).
Also some other minor changes.
> Refactor test circuits

- fault/test_vectors.py
- fault/verilator_target.py
- tests/common.py
- tests/test_test_vectors.py
This is a one-to-one copy of some magma testing infrastructure, moving it to the new repository. Also added some basic tests.
> Migrate magma testing infrastructure to fault

- fault/select_path.py
- fault/verilator_target.py
- fault/verilog_target.py
- fault/wrapper.py
- tests/test_setattr_interface.py
> Add support for arrays/tuples to setattr interface

- .travis.yml
- fault/random.py
- fault/verilator_target.py
- setup.py
- tests/test_constrained_random.py
require https://github.com/leonardt/hwtypes/pull/23
> Constrained random

- fault/actions.py
- fault/magma_simulator_target.py
- fault/system_verilog_target.py
- fault/tester.py
- fault/verilator_target.py
- fault/verilog_target.py
- tests/test_action.py
- tests/test_magma_simulator_target.py
- tests/test_tester.py
- tests/test_vector_builder.py
- tests/test_verilator_target.py
- tests/test_verilog_target.py
Upstream version of the branch in https://github.com/leonardt/fault/pull/84 (can't push to it because it's a fork)
> Aetherling debugging

- fault/system_verilog_target.py
- fault/verilator_target.py
- tests/test_verilog_target.py
Captures stdout and uses `logging` to report, removes default `print` statements and replaces with `logging`
> Capture stdout

- .travis.yml
- fault/cosa_target.py
- tests/test_symbolic_tester.py
Fixes https://github.com/leonardt/fault/issues/129
> Updates for latest cosa

- tests/test_select_model.py
This is a very minor PR to correct a failing pycodestyle test that was causing the master branch to be marked as "failing"
> Minor formatting fix to correct failing pycodestyle test

- fault/tester.py
- tests/common.py
- tests/test_tester.py
Addresses https://github.com/leonardt/fault/issues/154
See https://github.com/leonardt/fault/compare/tuple-actions?expand=1#diff-de403c371b3cd6c4725f37fb3a2fe531R548-R592 for example usage
> Add support for poke/expect dictionary for tuples

- README.md
- fault/system_verilog_target.py
- fault/verilator_target.py
- tests/test_setattr_interface.py
Addresses https://github.com/leonardt/fault/issues/155
See https://github.com/leonardt/fault/compare/print-internal-signals?expand=1#diff-be25ab5c75d3019d597f051e308a886cR48-R49 and https://github.com/leonardt/fault/compare/print-internal-signals?expand=1#diff-be25ab5c75d3019d597f051e308a886cR71
for an example, I'll add docs when I get a chance.
> Add support for printing internal signals

- fault/verilator_target.py
- tests/common.py
- tests/test_tester.py
Addresses https://github.com/leonardt/fault/issues/168
> Re-enable max_bits logic

- fault/select_path.py
Fixes https://github.com/leonardt/fault/issues/160#event-2671566864
> Use verilator_name for select path to verilator path

- .buildkite/pipeline.yml
This PR adds a YAML file containing the BuildKite test configuration.  Our BuildKite infrastructure has not be updated to use this file yet, but by merging this PR we should be able to make that change as seamlessly as possible.
> Add .buildkite/pipeline.yml

- .travis.yml
- fault/system_verilog_target.py
- tests/test_system_verilog_target.py
This can be used together with properties etc.
I don't have access to OSX so I have no idea how to fix brew. It seems like the OSX setup somehow is outdated/wrong, although I didn't change anything with the travis config.
> Add an option to use SVA

- tests/test_select_model.py
Update gold files for https://github.com/rdaly525/coreir/pull/839 and https://github.com/leonardt/verilogAST-cpp/pull/39
> Update gold for unsorted ports

- tests/test_select_model.py
Update golds for https://github.com/leonardt/verilogAST-cpp/pull/37
> Coreir linebreaks

- .buildkite/pipeline.yml
- .travis.yml
- fault/elect_type.py
- fault/real_type.py
Depends on https://github.com/phanrahan/magma/pull/585
> Update for magma wire IR

- fault/magma_simulator_target.py
- tests/test_magma_simulator_target.py
- tests/test_setattr_interface.py
- tests/test_tester.py
Adds tests for using the setattr interface, depends on https://github.com/phanrahan/magma/pull/588
> Update Python simulator target for magma 2

- .buildkite/pipeline.yml
- fault/elect_type.py
- fault/real_type.py
- tests/test_real_val.py
> Fix Real/Elect API

- setup.py
This PR is a one-character change to bump the version from 3.0.8 to 3.0.9 (sorry for the spam -- I'm not able to push to ``master`` myself)
> Release 3.0.9

- fault/value_utils.py
- fault/verilator_target.py
Few enhancements needed for testing garnet PE data gating. think they should be robust and generally good.
> Test pe data gate enhancements

- .travis.yml
- fault/subprocess_run.py
See
https://stackoverflow.com/questions/1445627/how-can-i-find-out-why-subprocess-popen-wait-waits-forever-if-stdout-pipe
for some more details
> Fix deadlock in subprocess logic

- fault/value_utils.py
- tests/test_magma_protocol.py
Adds initial support for https://github.com/cdonovick/peak/issues/154#issuecomment-618686502
> Support poking protocol values

- fault/system_verilog_target.py
- fault/tester/staged_tester.py
- fault/verilator_target.py
- tests/test_expressions.py
- tests/test_tester/test_core.py
Depends on https://github.com/phanrahan/magma/pull/768
> Fix wait until bug

- fault/verilog_target.py
- tests/test_tester/test_magma_usernamespace.py
Adds support for magma's user_namespace option (generated TB needs to be aware that the final circuit name will have changed)
> Fix user_namespace bug

- README.md
- fault/select_path.py
- fault/system_verilog_target.py
- fault/verilog_target.py
- fault/verilog_utils.py
- setup.py
- tests/test_select_model.py
- tests/test_setattr_interface.py
- tests/test_system_verilog_target.py
- tests/test_tester/test_call.py
- tests/test_tester/test_core.py
- tests/test_tester/test_magma_usernamespace.py
- tests/test_tester/test_synchronous.py
- tests/test_tester/test_timing.py
- tests/test_verilog_target.py
Depends on https://github.com/phanrahan/magma/pull/777 (which in turn depends on this for the test suite)
> Add support for magma/coreir verilog ndarrays

- tests/test_select_model.py
> Update gold for upstream coreir change

- doc/property.md
- setup.cfg
- tests/test_property.py
Depends on https://github.com/phanrahan/magma/pull/834
> Add test/example for default clock/reset in properties

- .buildkite/pipeline.yml
- fault/system_verilog_target.py
- tests/test_system_verilog_target.py
Since `irun` and `xrun` have the exact same commands, I just merge them together for better readability and easier maintenance.
> add xcelium support

- README.md
- fault/system_verilog_target.py
- fault/tester/staged_tester.py
- fault/verilator_target.py
- tests/test_tester/test_core.py
Feature request from @kavyasreedhar to just generate a test bench (without running it)
> Add API to just generate TB file

- doc/assert_immediate.md
- fault/__init__.py
- fault/assert_immediate.py
- tests/test_assert_immediate.py
Adds support for verilog style immediate assertion syntax
> Imm assert

- fault/property.py
- tests/test_property.py
Tracking down a bug, this seems to work, but wasn't being tested
> Fix bug in f.sva and not operator

- doc/property.md
- fault/__init__.py
- fault/property.py
- tests/test_property.py
Similar to `assert`, used as an assumption by formal tools
> Add assume

- fault/assert_immediate.py
- tests/test_assert_immediate.py
Useful for printing debug in formation when an assertion fails
> Support format args for imm assert failure msg

- fault/actions.py
- fault/system_verilog_target.py
- fault/tester/utils.py
- fault/verilator_target.py
- tests/test_tester/test_core.py
Known issue: 
https://github.com/leonardt/fault/blob/ff27d9466d25d98b277f953992bb0317cfe2e0be/fault/verilator_target.py#L596-L602
Not sure how to get sign from that. Maybe there is another class I should check?
> add support to poke and expect var

- fault/tester/base.py
This improves default mode performance by avoiding calls to the inspect
module when issuing `expect` actions.
Also improves the inspect logic to only fetch the desired frame rather
than using inspect.stack() to avoid constructing a list of frames
for the entire stack.
> Guard inspect logic behind debug_mode flag
